version: '3.8'
services: 
    class3d:
        # networks: 
        #    - testnet
        build: ./cidia-env/
        volumes: 
            - /home/guilherme/Documents/noa/cidia19/pipeline-app-3/data/:/data/
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
        # ports: 
        #    - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
            NVIDIA_DRIVER_CAPABILITIES: compute,utility,display
            DISPLAY: 
        network_mode: host
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities:
                            - gpu

# networks:
#    testnet:
#        driver: host
